-- ============================================================
-- SPILLERLOGG — Supabase-skjema
-- Kjør hele denne filen i Supabase Dashboard → SQL Editor → New query → Run
-- ============================================================

-- 1) PROFILER (én rad per bruker, kobles til Supabase Auth)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  role text not null default 'spiller' check (role in ('spiller', 'admin')),
  position text default '',
  created_at timestamptz default now()
);

alter table profiles enable row level security;

create policy "Alle innloggede kan se profiler"
  on profiles for select
  to authenticated
  using (true);

create policy "Bruker kan oppdatere egen profil"
  on profiles for update
  to authenticated
  using (auth.uid() = id);

-- Opprett automatisk en profilrad når en ny bruker registrerer seg
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role, position)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Ny bruker'),
    coalesce(new.raw_user_meta_data->>'role', 'spiller'),
    coalesce(new.raw_user_meta_data->>'position', '')
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Hjelpefunksjon: er brukeren admin?
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from profiles where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer stable;

-- 2) AKTIVITETER (trening/kamp-logg + spillform)
create table if not exists activities (
  id bigint generated by default as identity primary key,
  player_id uuid references profiles(id) on delete cascade not null,
  date date not null,
  type text not null check (type in ('Trening', 'Kamp')),
  status text not null check (status in ('Planlagt', 'Gjennomført', 'Fravær')),
  duration int default 0,
  spillform int check (spillform between 1 and 10),
  notat text default '',
  created_at timestamptz default now()
);

alter table activities enable row level security;

create policy "Spiller ser egne aktiviteter, admin ser alle"
  on activities for select
  to authenticated
  using (player_id = auth.uid() or is_admin());

create policy "Spiller kan legge inn egne aktiviteter"
  on activities for insert
  to authenticated
  with check (player_id = auth.uid() or is_admin());

create policy "Spiller kan endre egne aktiviteter, admin alle"
  on activities for update
  to authenticated
  using (player_id = auth.uid() or is_admin());

create policy "Spiller kan slette egne aktiviteter, admin alle"
  on activities for delete
  to authenticated
  using (player_id = auth.uid() or is_admin());

-- 3) SKADER (skadekartlegging)
create table if not exists injuries (
  id bigint generated by default as identity primary key,
  player_id uuid references profiles(id) on delete cascade not null,
  body_part text not null,
  dato date not null,
  alvorlighetsgrad text not null check (alvorlighetsgrad in ('Lett', 'Moderat', 'Alvorlig')),
  status text not null default 'Aktiv' check (status in ('Aktiv', 'Under behandling', 'Frisk')),
  forventet_tilbake date,
  notat text default '',
  created_at timestamptz default now()
);

alter table injuries enable row level security;

create policy "Spiller ser egne skader, admin ser alle"
  on injuries for select
  to authenticated
  using (player_id = auth.uid() or is_admin());

create policy "Spiller kan melde egne skader, admin for alle"
  on injuries for insert
  to authenticated
  with check (player_id = auth.uid() or is_admin());

create policy "Spiller kan endre egne skader, admin alle"
  on injuries for update
  to authenticated
  using (player_id = auth.uid() or is_admin());

create policy "Spiller kan slette egne skader, admin alle"
  on injuries for delete
  to authenticated
  using (player_id = auth.uid() or is_admin());
